name: dgnviewer
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal=3.8.*
  - proj=9.3.*         # helps the solver; gdal depends on proj anyway
  - geos=3.12.*        # helps the solver; gdal depends on geos anyway
  - streamlit=1.48.*
  - pydeck=0.9.*
  - pip
  - pip:
      - geojson
